# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            David Audet
tagline:          'Software Developer'
description:      
url:              
baseurl:          /

author:
  name:           'David Audet'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
