# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            David Audet
tagline:          'Software Developer'
description:      <img src="http://www.gravatar.com/avatar/ba0f2d1d32fe95ee0b53a723e3592e2b.png" />
url:              
baseurl:          /

author:
  name:           'David Audet'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
